### ISSUE TITLE
Installer should update default behavior

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/setup-dapr#9]
## Current behavior

The following yml:

```yml
- uses: dapr/setup-dapr@v1
```

defaults to install v1.2.0 of the Dapr CLI, which is out of date.

Users can specify a version to install the latest version:

```yml
- uses: dapr/setup-dapr@v1
  with:
    version: '1.3.0'
```

## Proposed behavior

There are two possible solutions we should explore:

### Option A: Default to the latest stable release

The following yml:

```yml
- uses: dapr/setup-dapr@v1
```

will now install the latest stable release. As the Dapr CLI continues to release new versions, the version installed by this yml will follow the latest release.

Users can still specify a version like the current behavior.

This is the behavior the `azure/setup-helm` uses
![image](https://user-images.githubusercontent.com/54363786/131000147-2baca453-33d0-4fb5-98c6-a85d3df132da.png)

### Option B: Require a version, and add a `latest` value

The following yml:

```yml
- uses: dapr/setup-dapr@v1
  with:
    version: 'latest'
```

will now install the latest stable release.

This forces users to opt-in to the latest release, instead of the latest release being the silent default.
